//! CCSDS pseudo-noise (PN) sequence de-randomizer.
//!
//! CCSDS 131.0-B-3 specifies a PN sequence generated by the
//! polynomial h(x) = x^8 + x^7 + x^5 + x^3 + 1, seeded with all
//! ones, period 255 bytes. The table itself is short enough that
//! medet ships it verbatim; we do the same and treat the medet
//! table as the canonical reference (it's been validated against
//! real Meteor downlinks for years).
//!
//! Frame bytes are `XOR`-ed with the PN stream during transmit to
//! break up long bit runs (helps the receiver's bit-clock stay
//! locked); receiver applies the same XOR to recover the original.
//! Sequence resets per CADU per spec — call [`Derandomizer::reset`]
//! at every CADU boundary.
//!
//! Reference (read-only): `original/medet/met_to_data.pas`
//! (the `prand` table at the top of the file) and dbdexter's
//! `meteor_decode/ecc/descramble.c` (`descramble_init`), which
//! generate the same 255-byte sequence two different ways.
//!
//! We do **not** hard-code the table: a hand-transcribed 255-byte
//! array is exactly how a silent corruption crept into an earlier
//! revision (51 wrong bytes from byte 82 on, which derandomized
//! every CADU into garbage and made over-the-air decoding
//! impossible). Instead [`generate_pn_table`] reproduces the spec
//! LFSR at compile time — it is a direct transliteration of
//! dbdexter's `descramble_init`, so the bytes are guaranteed
//! correct by construction and can never drift again.

/// Length of the CCSDS PN sequence (one period).
pub const PN_PERIOD: usize = 255;

/// LFSR seed for the CCSDS PN generator — all ones, per
/// CCSDS 131.0-B-3 / dbdexter `descramble_init` (`state = 0xFF`).
const PN_LFSR_SEED: u8 = 0xff;

/// Feedback tap bit positions for the polynomial
/// h(x) = x^8 + x^7 + x^5 + x^3 + 1 — combined by XOR into the new
/// high bit each shift (`descramble.c`: `(state>>7) ^ (state>>5) ^
/// (state>>3) ^ (state>>0)`).
const PN_LFSR_TAPS: [u8; 4] = [7, 5, 3, 0];

/// Generate the CCSDS PN sequence from the spec LFSR at compile
/// time (see [`PN_LFSR_SEED`] / [`PN_LFSR_TAPS`]). Each output byte
/// takes the register LSB MSB-first across 8 shifts. Byte-for-byte
/// transliteration of dbdexter's `descramble_init`
/// (`meteor_decode/ecc/descramble.c`); see the module docs for why
/// it is generated rather than tabulated.
const fn generate_pn_table() -> [u8; PN_PERIOD] {
    let mut table = [0_u8; PN_PERIOD];
    let mut state: u8 = PN_LFSR_SEED;
    let mut i = 0;
    while i < PN_PERIOD {
        let mut byte: u8 = 0;
        let mut bit = 0;
        while bit < 8 {
            // newbit = XOR of the tapped state bits.
            let mut newbit = 0_u8;
            let mut t = 0;
            while t < PN_LFSR_TAPS.len() {
                newbit ^= (state >> PN_LFSR_TAPS[t]) & 1;
                t += 1;
            }
            byte = (byte << 1) | (state & 1);
            state = (state >> 1) | (newbit << 7);
            bit += 1;
        }
        table[i] = byte;
        i += 1;
    }
    table
}

/// CCSDS PN table, generated from the spec LFSR (see
/// [`generate_pn_table`]). Matches medet's `prand` and dbdexter's
/// `descramble_init` byte-for-byte.
const PN_TABLE: [u8; PN_PERIOD] = generate_pn_table();

/// Streaming de-randomizer. Stateful position counter; XORs each
/// input byte against the pre-computed PN table.
pub struct Derandomizer {
    pos: usize,
}

impl Default for Derandomizer {
    fn default() -> Self {
        Self::new()
    }
}

impl Derandomizer {
    #[must_use]
    pub fn new() -> Self {
        Self { pos: 0 }
    }

    /// Reset the PN-sequence position. Call at every CADU boundary
    /// — the spec restarts the sequence per CADU.
    pub fn reset(&mut self) {
        self.pos = 0;
    }

    /// Push one byte; returns the de-randomized byte.
    pub fn process(&mut self, byte: u8) -> u8 {
        let out = byte ^ PN_TABLE[self.pos];
        // Branch-wrap instead of `% PN_PERIOD`: avoids a division
        // on every byte in the hot path. The compiler is welcome
        // to recognize the `% 255` modulus and emit the same code,
        // but the branch form is unambiguously cheap.
        self.pos += 1;
        if self.pos == PN_PERIOD {
            self.pos = 0;
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pn_table_starts_with_documented_bytes() {
        // First two bytes are the canonical 0xFF, 0x48 fingerprint
        // — anyone studying CCSDS PN sequences sees these in
        // every reference implementation.
        assert_eq!(PN_TABLE[0], 0xFF, "first PN byte");
        assert_eq!(PN_TABLE[1], 0x48, "second PN byte");
    }

    #[test]
    fn pn_table_matches_authoritative_sequence() {
        // Spot-check bytes against the canonical sequence produced
        // by dbdexter's `descramble_init` and medet's `prand`. The
        // chosen indices include the exact bytes a prior revision
        // corrupted (82, 137, 143, 175, 254) — if the LFSR taps or
        // direction ever regress, these fire immediately.
        const CHECKS: &[(usize, u8)] = &[
            (0, 0xff),
            (1, 0x48),
            (7, 0xbc),
            (82, 0xf7),
            (137, 0xc9),
            (143, 0xe5),
            (175, 0xcb),
            (242, 0xe6),
            (254, 0x58),
        ];
        for &(idx, want) in CHECKS {
            assert_eq!(
                PN_TABLE[idx], want,
                "PN byte {idx} = {:#04x}, expected {want:#04x}",
                PN_TABLE[idx],
            );
        }
    }

    #[test]
    fn pn_table_length_is_one_full_period() {
        assert_eq!(PN_TABLE.len(), PN_PERIOD);
    }

    #[test]
    fn round_trip_recovers_input() {
        // XOR is its own inverse and reset() puts us back at
        // position 0, so de-randomizing a randomized stream
        // recovers the original bytes exactly.
        let input: Vec<u8> = (0..100).collect();
        let mut d = Derandomizer::new();
        let scrambled: Vec<u8> = input.iter().map(|b| d.process(*b)).collect();
        d.reset();
        let recovered: Vec<u8> = scrambled.iter().map(|b| d.process(*b)).collect();
        assert_eq!(recovered, input);
    }

    #[test]
    fn position_wraps_at_period() {
        let mut d = Derandomizer::new();
        // Push PN_PERIOD + 5 zero bytes — XOR mask at byte
        // PN_PERIOD must equal the mask at byte 0.
        let masks: Vec<u8> = (0..PN_PERIOD + 5).map(|_| d.process(0)).collect();
        for offset in 0..5 {
            assert_eq!(
                masks[PN_PERIOD + offset],
                masks[offset],
                "PN sequence didn't wrap at byte {}",
                PN_PERIOD + offset,
            );
        }
    }
}
